'use strict';

const express = require('express');
const bcrypt  = require('bcrypt');
const router  = express.Router();

const { USERS_FILE }                              = require('../config/env');
const { loadData, saveData }                      = require('../storage/store');
const { generateRecoveryKey, formatRecoveryKey, logAudit } = require('./auth');
const validate                                    = require('../middleware/validate');

// ---------------------------------------------------------------------------
// GET /api/account/profile
// ---------------------------------------------------------------------------
router.get('/profile', (req, res) => {
    const users = loadData(USERS_FILE, {});
    res.json({
        success:          true,
        username:         users.adminUsername    || '',
        name:             users.adminName        || '',
        email:            users.adminEmail       || '',
        securityQuestion: users.securityQuestion || '', // Kept for display; no longer used for recovery
    });
});

// ---------------------------------------------------------------------------
// POST /api/account/update
// ---------------------------------------------------------------------------
router.post('/update', validate.accountUpdate, async (req, res) => {
    const users = loadData(USERS_FILE, {});
    const { username, password, name, email } = req.body;

    let updated    = false;
    let logMessage = [];

    if (username && username !== users.adminUsername) {
        users.adminUsername = username;
        updated = true;
        logMessage.push('username updated');
    }
    if (password) {
        users.adminHash = await bcrypt.hash(password, 10);
        updated = true;
        logMessage.push('password updated');
    }
    if (name !== undefined && name !== users.adminName) {
        users.adminName = name;
        updated = true;
        logMessage.push('name updated');
    }
    if (email !== undefined && email !== users.adminEmail) {
        users.adminEmail = email;
        updated = true;
        logMessage.push('email updated');
    }

    if (updated) {
        saveData(USERS_FILE, users);
        logAudit('ACCOUNT_UPDATED', req.ip, logMessage.join(', '));
        res.json({ success: true, message: 'Account updated successfully' });
    } else {
        res.json({ success: true, message: 'No changes made' });
    }
});

// ---------------------------------------------------------------------------
// GET /api/account/recovery-key  (generates a fresh key, invalidates old one)
// ---------------------------------------------------------------------------
router.get('/recovery-key', async (req, res) => {
    const users = loadData(USERS_FILE, {});
    try {
        const recoveryKey  = generateRecoveryKey();
        users.recoveryHash = await bcrypt.hash(recoveryKey, 10);
        saveData(USERS_FILE, users);
        logAudit('RECOVERY_KEY_GENERATED', req.ip, 'New recovery key generated by user');
        res.json({ success: true, recoveryKey: formatRecoveryKey(recoveryKey) });
    } catch (err) {
        console.error('[account] recovery-key error:', err);
        res.status(500).json({ success: false, message: 'Error generating recovery key' });
    }
});

// ---------------------------------------------------------------------------
// POST /api/account/reset-password
// Accepts recovery key ONLY. Security-question path has been removed.
// ---------------------------------------------------------------------------
router.post('/reset-password', validate.resetPassword, async (req, res) => {
    const users = loadData(USERS_FILE, {});
    const { recoveryKey, newPassword } = req.body;

    if (!newPassword) {
        return res.status(400).json({ success: false, message: 'New password is required' });
    }

    try {
        let match = false;

        if (recoveryKey && users.recoveryHash) {
            const normalizedKey = recoveryKey.replace(/-/g, '').toUpperCase();
            match = await bcrypt.compare(normalizedKey, users.recoveryHash);
        }

        if (match) {
            users.adminHash = await bcrypt.hash(newPassword, 10);
            // Rotate the recovery key so the used key cannot be replayed
            const newRecoveryKey  = generateRecoveryKey();
            users.recoveryHash    = await bcrypt.hash(newRecoveryKey, 10);

            saveData(USERS_FILE, users);
            logAudit('PASSWORD_RESET', req.ip, 'Password reset via recovery key');
            res.json({
                success:     true,
                message:     'Password reset successfully',
                recoveryKey: formatRecoveryKey(newRecoveryKey),
            });
        } else {
            logAudit('PASSWORD_RESET_FAILED', req.ip, 'Invalid recovery key');
            res.status(401).json({ success: false, message: 'Invalid recovery key' });
        }
    } catch (err) {
        console.error('[account] reset-password error:', err);
        res.status(500).json({ success: false, message: 'Error resetting password' });
    }
});

// ---------------------------------------------------------------------------
// GET /api/account/security-question  — DEPRECATED (410 Gone)
// ---------------------------------------------------------------------------
router.get('/security-question', (req, res) => {
    res.status(410).json({
        success: false,
        message: 'Security-question recovery has been removed. Use your recovery key instead.',
        deprecatedSince: '2.2.0',
    });
});

// ---------------------------------------------------------------------------
// POST /api/account/delete  (factory reset; requires password confirmation)
// ---------------------------------------------------------------------------
router.post('/delete', validate.accountDelete, async (req, res) => {
    const { SETTINGS_FILE } = require('../config/env');
    const { applyFilter }   = require('../system/dns');

    try {
        const { password } = req.body;
        const users        = loadData(USERS_FILE, {});

        if (!password) {
            return res.status(400).json({ success: false, message: 'Password required to delete account.' });
        }

        const match = await bcrypt.compare(password, users.adminHash);
        if (!match) {
            logAudit('ACCOUNT_DELETE_FAILED', req.ip, 'Invalid password provided for account deletion.');
            return res.status(401).json({ success: false, message: 'Invalid password for account deletion.' });
        }

        const fs = require('fs');
        if (fs.existsSync(USERS_FILE)) fs.unlinkSync(USERS_FILE);

        const resetSettings = {
            filterLevel:      'off',
            lockdownMode:     false,
            network:          { dnsPrimary: '', dnsSecondary: '' },
            vpn:              { hostname: '', hub: '', port: '' },
            personalization:  { theme: 'dark', accentColor: '#4f46e5' },
            accountability:   { enabled: false, partners: [] },
            blockedApps:      [],
        };
        saveData(SETTINGS_FILE, resetSettings);
        applyFilter('off');

        logAudit('ACCOUNT_DELETED', req.ip, 'User deleted account and factory reset system');
        res.json({ success: true, message: 'Account deleted and system reset.' });
    } catch (err) {
        console.error('[account] delete error:', err);
        res.status(500).json({ success: false, message: 'Error deleting account' });
    }
});

module.exports = router;
