name: Build Mobile Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install Dependencies
      run: pnpm install

    - name: Build Android Release
      run: pnpm --filter @pb/mobile-client build:android

  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install Dependencies
      run: pnpm install

    - name: Build iOS Release
      run: pnpm --filter @pb/mobile-client build:ios
